version: "3.9"

networks:
  dev-network:
    driver: bridge

services:
  dev-db:
    image: postgres:16.3-alpine3.20
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - ./.env
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - dev-network

  # test-db:
  #   image: postgres:16.3-alpine3.20
  #   restart: always
  #   ports:
  #     - "5434:5432"
  #   env_file:
  #     - ./.env
  #   volumes:
  #     - ./scripts:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - dev-network

name: fastapi-development
